import os
import datetime
from io import BytesIO

def save_document(response_text: str, directory: str = "./output"):
    """Export travel plan to a Markdown file with proper formatting.

    Returns the path to the saved markdown file or None on error.
    """
    os.makedirs(directory, exist_ok=True)

    markdown_content = (
        f"# 🌍 AI Travel Plan\n\n"
        f"**Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}\n"
        f"**Created by:** GetSetGoAI Travel Agent\n\n"
        "---\n\n"
        f"{response_text}\n\n"
        "---\n\n"
        f"*This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*\n"
    )

    try:
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = os.path.join(directory, f"AI_Trip_Planner_{timestamp}.md")
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(markdown_content)
        return filename
    except Exception as e:
        print(f"Error saving markdown file: {e}")
        return None


def markdown_to_pdf_bytes(markdown_text: str, title: str = "Travel Plan") -> bytes:
    """Render high-end PDF with proper styling using ReportLab Platypus."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
        from reportlab.lib import colors
        from reportlab.lib.units import inch
        import re
    except ImportError:
        raise RuntimeError("Missing dependency: reportlab. Install with `pip install reportlab`")

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, 
        pagesize=A4,
        rightMargin=inch*0.75,
        leftMargin=inch*0.75,
        topMargin=inch*0.75,
        bottomMargin=inch*0.75
    )

    styles = getSampleStyleSheet()
    
    # Custom Premium Styles
    styles.add(ParagraphStyle(
        name='PremiumTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor("#1A1A1A"),
        spaceAfter=20,
        alignment=1 # Center
    ))
    
    styles.add(ParagraphStyle(
        name='PremiumH2',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor("#2C3E50"),
        spaceBefore=15,
        spaceAfter=10,
        borderPadding=(0, 0, 2, 0),
        borderWidth=0,
        borderStyle=None
    ))

    styles.add(ParagraphStyle(
        name='PremiumBody',
        parent=styles['Normal'],
        fontSize=11,
        leading=14,
        textColor=colors.HexColor("#333333"),
        spaceAfter=8
    ))

    story = []

    # Header
    story.append(Paragraph(f"<b>{title}</b>", styles['PremiumTitle']))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey, spaceAfter=20))

    # Basic Markdown to Platypus conversion
    lines = markdown_text.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            story.append(Spacer(1, 0.1*inch))
            continue
        
        # Headers
        if line.startswith('## '):
            story.append(Paragraph(line[3:], styles['PremiumH2']))
        elif line.startswith('### '):
            story.append(Paragraph(f"<b>{line[4:]}</b>", styles['Heading3']))
        else:
            # Simple bold/italic conversion
            clean_line = line
            clean_line = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', clean_line)
            clean_line = re.sub(r'\*(.*?)\*', r'<i>\1</i>', clean_line)
            # Handle list items
            if line.startswith('- '):
                story.append(Paragraph(f"&bull; {clean_line[2:]}", styles['PremiumBody']))
            else:
                story.append(Paragraph(clean_line, styles['PremiumBody']))

    # Footer/Disclaimer
    story.append(Spacer(1, 0.5*inch))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey, spaceBefore=10))
    disclaimer = ("<i>This travel plan was curated by GetSetGo AI. Please verify bookings and "
                  "local conditions before travel. Prices are approximate.</i>")
    story.append(Paragraph(disclaimer, styles['Normal']))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()